CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Username] NVARCHAR(50) NOT NULL, 
    [EmailAddress] NVARCHAR(50) NOT NULL, 
    [Password] BINARY(64) NOT NULL, 
    [Xp] INT NOT NULL DEFAULT 0, 
    [Level] INT NOT NULL DEFAULT 1
)
